version: '3.9'

volumes:
  media:
  static:
  un_mysql_data:
  un_portainer_data:
  redis_data:
  esep_updater_ninja_un_mysql_data:
    external: true

networks:
  un-net:
    driver: bridge

services:
  ninja-server:
    container_name: ninja-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/updaterninja
      - media:/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - MYSQL_HOST=db
      - MYSQL_DATABASE=updaterninja
      - MYSQL_ROOT_PASSWORD=ninjapassword
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=ninjapassword
      - UPLOAD_LIMIT=300M
      - ESEP_DB_HOST=192.168.1.17
      - ESEP_DB_USER=sultan_a
      - ESEP_DB_PASSWORD=L$$xUQyBQ
      - ESEP_DB_NAME=esep
    ports:
      - "8008:8000"
    depends_on:
      - db
    networks:
      - un-net

  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
      - esep_updater_ninja_un_mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=updaterninja
      - MYSQL_ROOT_PASSWORD=ninjapassword
    networks:
      - un-net
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=ninjapassword
    networks:
      - un-net
    ports:
      - "8080:80"
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini

  ninja-beat:
    container_name: ninja-beat
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/updaterninja
      - media:/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - ESEP_DB_HOST=192.168.1.17
      - ESEP_DB_USER=sultan_a
      - ESEP_DB_PASSWORD=L$$xUQyBQ
      - ESEP_DB_NAME=esep
    depends_on:
      - ninja-worker
      - ninja-server
    networks:
      - un-net
    command: "celery -A config.celery_app beat --loglevel=INFO"

  ninja-worker:
    container_name: ninja-worker
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/updaterninja
      - media:/media
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - ESEP_DB_HOST=192.168.1.17
      - ESEP_DB_USER=sultan_a
      - ESEP_DB_PASSWORD=L$$xUQyBQ
      - ESEP_DB_NAME=esep
    networks:
      - un-net
    command: "celery -A config.celery_app worker --loglevel=INFO"

  ninja-portainer:
    container_name: ninja-portainer
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      - TZ=Asia/Almaty
    ports:
      - "9009:9000"
    volumes:
      - un_portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - un-net

  ninja-redis:
    container_name: ninja-redis
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes --replica-read-only no
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - un-net
