# Generated by Django 4.2.11 on 2024-05-01 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HandledException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('code', models.CharField(max_length=256, verbose_name='Код ошибки')),
                ('message', models.CharField(max_length=256, verbose_name='Описание ошибки')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='Traceback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('updating_type', models.CharField(choices=[('BY_API', 'Через API'), ('BY_FILE', 'Через Файл')], default='BY_API', max_length=20)),
                ('data_file', models.FileField(null=True, upload_to='')),
                ('account_numbers', models.TextField(null=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('IN_PROCESS', 'В процессе'), ('FAILED', 'Неуспешно')], default='SUCCESS', max_length=20)),
                ('status_reason', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
