# Generated by Django 4.2.11 on 2024-05-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='account_numbers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='updatehistory',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='updatehistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('IN_PROCESS', 'В процессе'), ('FAILED', 'Неуспешно')], default='IN_PROCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='updatehistory',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
