# Generated by Django 4.2.11 on 2024-05-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_updatehistory_account_numbers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatehistory',
            options={'verbose_name': 'Обновление', 'verbose_name_plural': 'История Обновлений'},
        ),
    ]
