# Generated by Django 4.2.11 on 2024-05-01 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_updatehistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('result_type', models.CharField(choices=[('IN_ACA_NOT_IN_ESEP', 'Есть в АСА, но нет в Есеп'), ('IN_ESEP_NOT_IN_ACA', 'Есть в Есеп, но нет в АСА'), ('ADDED_NEW_DEVICES', 'Добавлены Новые Девайсы'), ('REMOVED_REDUNDANT_DEVICES', 'Удалены Лишние Девайсы')], default='IN_ACA_NOT_IN_ESEP', max_length=30)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('update_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='common.updatehistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
