# Generated by Django 4.2.11 on 2024-05-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_updatehistoryreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatehistory',
            name='account_numbers',
        ),
        migrations.AlterField(
            model_name='updatehistoryreport',
            name='result_type',
            field=models.CharField(choices=[('ZERO_IN_ACA_NOT_IN_ESEP', '0 в АСА, нет в Есеп'), ('IN_ACA_NOT_IN_ESEP', 'Есть в АСА, но нет в Есеп'), ('IN_ESEP_NOT_IN_ACA', 'Есть в Есеп, но нет в АСА'), ('ADDED_NEW_DEVICES', 'Добавлены Новые Девайсы'), ('REMOVED_REDUNDANT_DEVICES', 'Удалены Лишние Девайсы')], default='IN_ACA_NOT_IN_ESEP', max_length=30),
        ),
    ]
