# Generated by Django 4.2.11 on 2024-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_result_type_updatehistoryreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='data'),
        ),
    ]
