# Generated by Django 4.2.11 on 2024-05-16 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_updatehistory_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistoryreport',
            name='report_type',
            field=models.CharField(choices=[('ZERO_IN_ACA_NOT_IN_ESEP', '0 в АСА, нет в Есеп'), ('IN_ACA_NOT_IN_ESEP', 'Есть в АСА, но нет в Есеп'), ('IN_ACA_NO_ACCOUNT_IN_ESEP', 'Есть в АСА, но нет в Есепе даже ЛС'), ('IN_ESEP_NOT_IN_ACA', 'Есть в Есеп, но нет в АСА'), ('ADDED_NEW_DEVICES', 'Добавлены Новые Счетчики'), ('REMOVED_REDUNDANT_DEVICES', 'Удалены Лишние Счетчики'), ('SUCCESSFULLY_UPDATED_DEVICES', 'Успешно обновленные Счетчики')], default='IN_ACA_NOT_IN_ESEP', max_length=30),
        ),
        migrations.CreateModel(
            name='UpdateHistoryRollback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('update_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rollback', to='common.updatehistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
