# Generated by Django 4.2.11 on 2024-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_updatehistoryreport_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Успешно'), ('IN_PROCESS', 'В процессе'), ('FAILED', 'Неуспешно'), ('ROLLED_BACK', 'Откатили изменения')], default='IN_PROCESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='updatehistoryreport',
            name='report_type',
            field=models.CharField(choices=[('ZERO_IN_ACA_NOT_IN_ESEP', '0 в АСА, нет в Есеп'), ('IN_ACA_NOT_IN_ESEP', 'Есть в АСА, но нет в Есеп'), ('IN_ACA_NO_ACCOUNT_IN_ESEP', 'Есть в АСА, но нет в Есепе даже ЛС'), ('IN_ESEP_NOT_IN_ACA', 'Есть в Есеп, но нет в АСА'), ('ADDED_NEW_DEVICES', 'Добавлены Новые Счетчики'), ('REMOVED_REDUNDANT_DEVICES', 'Удалены Лишние Счетчики'), ('SUCCESSFULLY_UPDATED_DEVICES', 'Успешно обновленные Счетчики'), ('EMPTY_BODY_FROM_ACA_API', 'Пустой объект от ACA API')], default='IN_ACA_NOT_IN_ESEP', max_length=30),
        ),
    ]
