# Generated by Django 4.2.11 on 2024-07-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_updatehistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatehistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания запуска'),
        ),
        migrations.AddField(
            model_name='updatehistory',
            name='rolled_back_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отката'),
        ),
    ]
