# Generated by Django 5.2.3 on 2025-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_updatehistory_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="updatehistoryreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("ZERO_IN_VODOKANAL_NOT_IN_ESEP", "0 в VODOKANAL, нет в Есеп"),
                    ("IN_VODOKANAL_NOT_IN_ESEP", "Есть в VODOKANAL, но нет в Есеп"),
                    (
                        "IN_VODOKANAL_NO_ACCOUNT_IN_ESEP",
                        "Есть в VODOKANAL, но нет в Есепе даже ЛС",
                    ),
                    ("IN_ESEP_NOT_IN_VODOKANAL", "Есть в Есеп, но нет в VODOKANAL"),
                    ("ADDED_NEW_DEVICES", "Добавлены Новые Счетчики"),
                    ("REMOVED_REDUNDANT_DEVICES", "Удалены Лишние Счетчики"),
                    ("SUCCESSFULLY_UPDATED_DEVICES", "Успешно обновленные Счетчики"),
                    ("EMPTY_BODY_FROM_VODOKANAL_API", "Пустой объект от VODOKANAL API"),
                ],
                default="IN_VODOKANAL_NOT_IN_ESEP",
                max_length=100,
            ),
        ),
    ]
