# Generated by Django 5.2.3 on 2025-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_updatehistoryreport_report_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="updatehistory",
            name="company_id",
            field=models.PositiveIntegerField(
                choices=[(7, "ACA"), (10, "Кокшетау")],
                default=7,
                verbose_name="Компания",
            ),
        ),
    ]
